"""add at

Revision ID: bf896e501a09
Revises: 0bd0a3ac7618
Create Date: 2024-11-10 13:04:58.638859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import delete


# revision identifiers, used by Alembic.
revision: str = 'bf896e501a09'
down_revision: Union[str, None] = '0bd0a3ac7618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM trips;')
    op.add_column('trips', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('trips', sa.Column('end_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'end_at')
    op.drop_column('trips', 'start_at')
    # ### end Alembic commands ###
